part of 'smart_food_suggestions.dart';

const List<_CatalogFoodEntry> _extendedCatalog = <_CatalogFoodEntry>[
  _CatalogFoodEntry(
    nameEn: 'Mozzarella',
    nameRu: 'Моцарелла',
    categoryEn: 'Dairy',
    categoryRu: 'Молочное',
    pantryUnit: 'GRAM',
    quantity: '200',
    aliasesEn: <String>['mozzarella cheese'],
    aliasesRu: <String>['сыр моцарелла'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Parmesan',
    nameRu: 'Пармезан',
    categoryEn: 'Dairy',
    categoryRu: 'Молочное',
    pantryUnit: 'GRAM',
    quantity: '150',
    aliasesEn: <String>['parmesan cheese'],
    aliasesRu: <String>['сыр пармезан'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Ricotta',
    nameRu: 'Рикотта',
    categoryEn: 'Dairy',
    categoryRu: 'Молочное',
    pantryUnit: 'PACK',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Cream cheese',
    nameRu: 'Сливочный сыр',
    categoryEn: 'Dairy',
    categoryRu: 'Молочное',
    pantryUnit: 'PACK',
    quantity: '1',
    aliasesEn: <String>['philadelphia'],
    aliasesRu: <String>['крем сыр'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Skyr',
    nameRu: 'Скир',
    categoryEn: 'Dairy',
    categoryRu: 'Молочное',
    pantryUnit: 'PACK',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Coconut milk',
    nameRu: 'Кокосовое молоко',
    categoryEn: 'Beverages',
    categoryRu: 'Напитки',
    pantryUnit: 'CAN',
    quantity: '1',
    aliasesEn: <String>['coconut cream'],
    aliasesRu: <String>['кокосовые сливки'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Almond milk',
    nameRu: 'Миндальное молоко',
    categoryEn: 'Beverages',
    categoryRu: 'Напитки',
    pantryUnit: 'LITER',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Oat milk',
    nameRu: 'Овсяное молоко',
    categoryEn: 'Beverages',
    categoryRu: 'Напитки',
    pantryUnit: 'LITER',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Shrimp',
    nameRu: 'Креветки',
    categoryEn: 'Seafood',
    categoryRu: 'Морепродукты',
    pantryUnit: 'GRAM',
    quantity: '400',
    aliasesEn: <String>['prawns'],
    aliasesRu: <String>['тигровые креветки'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Cod fillet',
    nameRu: 'Филе трески',
    categoryEn: 'Fish',
    categoryRu: 'Рыба',
    pantryUnit: 'GRAM',
    quantity: '400',
    aliasesEn: <String>['cod'],
    aliasesRu: <String>['треска'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Tilapia',
    nameRu: 'Тилапия',
    categoryEn: 'Fish',
    categoryRu: 'Рыба',
    pantryUnit: 'GRAM',
    quantity: '400',
  ),
  _CatalogFoodEntry(
    nameEn: 'Pork loin',
    nameRu: 'Свиная корейка',
    categoryEn: 'Protein',
    categoryRu: 'Белок',
    pantryUnit: 'GRAM',
    quantity: '500',
    aliasesEn: <String>['pork'],
    aliasesRu: <String>['свинина'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Beef steak',
    nameRu: 'Говяжий стейк',
    categoryEn: 'Protein',
    categoryRu: 'Белок',
    pantryUnit: 'GRAM',
    quantity: '400',
    aliasesEn: <String>['steak'],
    aliasesRu: <String>['стейк'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Chicken thighs',
    nameRu: 'Куриные бедра',
    categoryEn: 'Protein',
    categoryRu: 'Белок',
    pantryUnit: 'GRAM',
    quantity: '700',
  ),
  _CatalogFoodEntry(
    nameEn: 'Chicken wings',
    nameRu: 'Куриные крылышки',
    categoryEn: 'Protein',
    categoryRu: 'Белок',
    pantryUnit: 'GRAM',
    quantity: '800',
  ),
  _CatalogFoodEntry(
    nameEn: 'Minced turkey',
    nameRu: 'Фарш из индейки',
    categoryEn: 'Protein',
    categoryRu: 'Белок',
    pantryUnit: 'GRAM',
    quantity: '500',
  ),
  _CatalogFoodEntry(
    nameEn: 'Bacon',
    nameRu: 'Бекон',
    categoryEn: 'Protein',
    categoryRu: 'Белок',
    pantryUnit: 'PACK',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Ham',
    nameRu: 'Ветчина',
    categoryEn: 'Protein',
    categoryRu: 'Белок',
    pantryUnit: 'PACK',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Tofu',
    nameRu: 'Тофу',
    categoryEn: 'Protein',
    categoryRu: 'Белок',
    pantryUnit: 'PACK',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Tempeh',
    nameRu: 'Темпе',
    categoryEn: 'Protein',
    categoryRu: 'Белок',
    pantryUnit: 'PACK',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Red lentils',
    nameRu: 'Красная чечевица',
    categoryEn: 'Pantry',
    categoryRu: 'Бакалея',
    pantryUnit: 'PACK',
    quantity: '1',
    aliasesEn: <String>['lentils'],
    aliasesRu: <String>['чечевица'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Green lentils',
    nameRu: 'Зеленая чечевица',
    categoryEn: 'Pantry',
    categoryRu: 'Бакалея',
    pantryUnit: 'PACK',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Quinoa',
    nameRu: 'Киноа',
    categoryEn: 'Grains',
    categoryRu: 'Крупы',
    pantryUnit: 'PACK',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Couscous',
    nameRu: 'Кускус',
    categoryEn: 'Grains',
    categoryRu: 'Крупы',
    pantryUnit: 'PACK',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Bulgur',
    nameRu: 'Булгур',
    categoryEn: 'Grains',
    categoryRu: 'Крупы',
    pantryUnit: 'PACK',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Rice noodles',
    nameRu: 'Рисовая лапша',
    categoryEn: 'Grains',
    categoryRu: 'Крупы',
    pantryUnit: 'PACK',
    quantity: '1',
    aliasesEn: <String>['noodles'],
    aliasesRu: <String>['лапша'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Udon noodles',
    nameRu: 'Лапша удон',
    categoryEn: 'Grains',
    categoryRu: 'Крупы',
    pantryUnit: 'PACK',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Tortillas',
    nameRu: 'Тортильи',
    categoryEn: 'Bakery',
    categoryRu: 'Выпечка',
    pantryUnit: 'PACK',
    quantity: '1',
    aliasesEn: <String>['wraps'],
    aliasesRu: <String>['лаваш для роллов'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Pita bread',
    nameRu: 'Пита',
    categoryEn: 'Bakery',
    categoryRu: 'Выпечка',
    pantryUnit: 'PACK',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Bagels',
    nameRu: 'Бейглы',
    categoryEn: 'Bakery',
    categoryRu: 'Выпечка',
    pantryUnit: 'PACK',
    quantity: '1',
    aliasesEn: <String>['bagel'],
    aliasesRu: <String>['бейгл'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Zucchini',
    nameRu: 'Кабачок',
    categoryEn: 'Vegetables',
    categoryRu: 'Овощи',
    pantryUnit: 'KILOGRAM',
    quantity: '1',
    aliasesEn: <String>['courgette'],
    aliasesRu: <String>['цукини'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Eggplant',
    nameRu: 'Баклажан',
    categoryEn: 'Vegetables',
    categoryRu: 'Овощи',
    pantryUnit: 'KILOGRAM',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Cauliflower',
    nameRu: 'Цветная капуста',
    categoryEn: 'Vegetables',
    categoryRu: 'Овощи',
    pantryUnit: 'PIECE',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Brussels sprouts',
    nameRu: 'Брюссельская капуста',
    categoryEn: 'Vegetables',
    categoryRu: 'Овощи',
    pantryUnit: 'GRAM',
    quantity: '400',
  ),
  _CatalogFoodEntry(
    nameEn: 'Cabbage',
    nameRu: 'Капуста',
    categoryEn: 'Vegetables',
    categoryRu: 'Овощи',
    pantryUnit: 'PIECE',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Beetroot',
    nameRu: 'Свекла',
    categoryEn: 'Vegetables',
    categoryRu: 'Овощи',
    pantryUnit: 'KILOGRAM',
    quantity: '1',
    aliasesEn: <String>['beets'],
    aliasesRu: <String>['свекла вареная'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Pumpkin',
    nameRu: 'Тыква',
    categoryEn: 'Vegetables',
    categoryRu: 'Овощи',
    pantryUnit: 'PIECE',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Celery',
    nameRu: 'Сельдерей',
    categoryEn: 'Vegetables',
    categoryRu: 'Овощи',
    pantryUnit: 'PIECE',
    quantity: '1',
    aliasesEn: <String>['celery stalks'],
    aliasesRu: <String>['стебли сельдерея'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Asparagus',
    nameRu: 'Спаржа',
    categoryEn: 'Vegetables',
    categoryRu: 'Овощи',
    pantryUnit: 'PACK',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Green peas',
    nameRu: 'Зеленый горошек',
    categoryEn: 'Vegetables',
    categoryRu: 'Овощи',
    pantryUnit: 'PACK',
    quantity: '1',
    aliasesEn: <String>['peas'],
    aliasesRu: <String>['горошек'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Corn',
    nameRu: 'Кукуруза',
    categoryEn: 'Vegetables',
    categoryRu: 'Овощи',
    pantryUnit: 'CAN',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Radish',
    nameRu: 'Редис',
    categoryEn: 'Vegetables',
    categoryRu: 'Овощи',
    pantryUnit: 'PACK',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Blueberries',
    nameRu: 'Черника',
    categoryEn: 'Fruits',
    categoryRu: 'Фрукты',
    pantryUnit: 'PACK',
    quantity: '1',
    aliasesEn: <String>['blueberry'],
    aliasesRu: <String>['голубика'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Strawberries',
    nameRu: 'Клубника',
    categoryEn: 'Fruits',
    categoryRu: 'Фрукты',
    pantryUnit: 'PACK',
    quantity: '1',
    aliasesEn: <String>['strawberry'],
    aliasesRu: <String>['ягоды'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Raspberries',
    nameRu: 'Малина',
    categoryEn: 'Fruits',
    categoryRu: 'Фрукты',
    pantryUnit: 'PACK',
    quantity: '1',
    aliasesEn: <String>['raspberry'],
    aliasesRu: <String>['ягоды малины'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Mango',
    nameRu: 'Манго',
    categoryEn: 'Fruits',
    categoryRu: 'Фрукты',
    pantryUnit: 'PIECE',
    quantity: '2',
  ),
  _CatalogFoodEntry(
    nameEn: 'Pineapple',
    nameRu: 'Ананас',
    categoryEn: 'Fruits',
    categoryRu: 'Фрукты',
    pantryUnit: 'PIECE',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Pears',
    nameRu: 'Груши',
    categoryEn: 'Fruits',
    categoryRu: 'Фрукты',
    pantryUnit: 'KILOGRAM',
    quantity: '1',
    aliasesEn: <String>['pear'],
    aliasesRu: <String>['груша'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Oranges',
    nameRu: 'Апельсины',
    categoryEn: 'Fruits',
    categoryRu: 'Фрукты',
    pantryUnit: 'KILOGRAM',
    quantity: '1',
    aliasesEn: <String>['orange'],
    aliasesRu: <String>['апельсин'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Grapes',
    nameRu: 'Виноград',
    categoryEn: 'Fruits',
    categoryRu: 'Фрукты',
    pantryUnit: 'PACK',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Kiwi',
    nameRu: 'Киви',
    categoryEn: 'Fruits',
    categoryRu: 'Фрукты',
    pantryUnit: 'PIECE',
    quantity: '4',
  ),
  _CatalogFoodEntry(
    nameEn: 'Peanut butter',
    nameRu: 'Арахисовая паста',
    categoryEn: 'Pantry',
    categoryRu: 'Бакалея',
    pantryUnit: 'JAR',
    quantity: '1',
    aliasesEn: <String>['peanut spread'],
    aliasesRu: <String>['паста арахисовая'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Jam',
    nameRu: 'Джем',
    categoryEn: 'Pantry',
    categoryRu: 'Бакалея',
    pantryUnit: 'JAR',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Honey',
    nameRu: 'Мед',
    categoryEn: 'Pantry',
    categoryRu: 'Бакалея',
    pantryUnit: 'JAR',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Soy sauce',
    nameRu: 'Соевый соус',
    categoryEn: 'Pantry',
    categoryRu: 'Бакалея',
    pantryUnit: 'BOTTLE',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Teriyaki sauce',
    nameRu: 'Соус терияки',
    categoryEn: 'Pantry',
    categoryRu: 'Бакалея',
    pantryUnit: 'BOTTLE',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Tomato paste',
    nameRu: 'Томатная паста',
    categoryEn: 'Pantry',
    categoryRu: 'Бакалея',
    pantryUnit: 'PACK',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Canned tomatoes',
    nameRu: 'Томаты в собственном соку',
    categoryEn: 'Pantry',
    categoryRu: 'Бакалея',
    pantryUnit: 'CAN',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Curry paste',
    nameRu: 'Паста карри',
    categoryEn: 'Spices',
    categoryRu: 'Специи',
    pantryUnit: 'JAR',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Paprika',
    nameRu: 'Паприка',
    categoryEn: 'Spices',
    categoryRu: 'Специи',
    pantryUnit: 'PACK',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Turmeric',
    nameRu: 'Куркума',
    categoryEn: 'Spices',
    categoryRu: 'Специи',
    pantryUnit: 'PACK',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Cinnamon',
    nameRu: 'Корица',
    categoryEn: 'Spices',
    categoryRu: 'Специи',
    pantryUnit: 'PACK',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Chia seeds',
    nameRu: 'Семена чиа',
    categoryEn: 'Pantry',
    categoryRu: 'Бакалея',
    pantryUnit: 'PACK',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Flax seeds',
    nameRu: 'Семена льна',
    categoryEn: 'Pantry',
    categoryRu: 'Бакалея',
    pantryUnit: 'PACK',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Walnuts',
    nameRu: 'Грецкие орехи',
    categoryEn: 'Pantry',
    categoryRu: 'Бакалея',
    pantryUnit: 'GRAM',
    quantity: '200',
    aliasesEn: <String>['walnut'],
    aliasesRu: <String>['орехи'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Almonds',
    nameRu: 'Миндаль',
    categoryEn: 'Pantry',
    categoryRu: 'Бакалея',
    pantryUnit: 'GRAM',
    quantity: '200',
  ),
  _CatalogFoodEntry(
    nameEn: 'Cashews',
    nameRu: 'Кешью',
    categoryEn: 'Pantry',
    categoryRu: 'Бакалея',
    pantryUnit: 'GRAM',
    quantity: '200',
  ),
  _CatalogFoodEntry(
    nameEn: 'Dark chocolate',
    nameRu: 'Темный шоколад',
    categoryEn: 'Snacks',
    categoryRu: 'Перекусы',
    pantryUnit: 'BAR',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Rice cakes',
    nameRu: 'Рисовые хлебцы',
    categoryEn: 'Snacks',
    categoryRu: 'Перекусы',
    pantryUnit: 'PACK',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Protein bar',
    nameRu: 'Протеиновый батончик',
    categoryEn: 'Snacks',
    categoryRu: 'Перекусы',
    pantryUnit: 'PIECE',
    quantity: '3',
  ),
  _CatalogFoodEntry(
    nameEn: 'Granola',
    nameRu: 'Гранола',
    categoryEn: 'Snacks',
    categoryRu: 'Перекусы',
    pantryUnit: 'PACK',
    quantity: '1',
    aliasesEn: <String>['muesli'],
    aliasesRu: <String>['мюсли'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Sparkling water',
    nameRu: 'Газированная вода',
    categoryEn: 'Beverages',
    categoryRu: 'Напитки',
    pantryUnit: 'BOTTLE',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Orange juice',
    nameRu: 'Апельсиновый сок',
    categoryEn: 'Beverages',
    categoryRu: 'Напитки',
    pantryUnit: 'LITER',
    quantity: '1',
    aliasesEn: <String>['juice'],
    aliasesRu: <String>['сок'],
  ),
  _CatalogFoodEntry(
    nameEn: 'Matcha',
    nameRu: 'Матча',
    categoryEn: 'Beverages',
    categoryRu: 'Напитки',
    pantryUnit: 'PACK',
    quantity: '1',
  ),
  _CatalogFoodEntry(
    nameEn: 'Protein powder',
    nameRu: 'Протеиновый порошок',
    categoryEn: 'Supplements',
    categoryRu: 'Добавки',
    pantryUnit: 'PACK',
    quantity: '1',
    aliasesEn: <String>['whey protein'],
    aliasesRu: <String>['сывороточный протеин'],
  ),
];

const List<_RecipePromptEntry> _extendedRecipePrompts = <_RecipePromptEntry>[
  _RecipePromptEntry(
    labelEn: 'Chicken rice bowl',
    labelRu: 'Рис боул с курицей',
    aliasesEn: <String>['rice bowl', 'chicken bowl'],
    aliasesRu: <String>['боул с курицей', 'рис с курицей'],
  ),
  _RecipePromptEntry(
    labelEn: 'Turkey cutlets',
    labelRu: 'Котлеты из индейки',
    aliasesEn: <String>['turkey patties'],
    aliasesRu: <String>['индейка котлеты'],
  ),
  _RecipePromptEntry(
    labelEn: 'Creamy pasta',
    labelRu: 'Сливочная паста',
    aliasesEn: <String>['creamy pasta'],
    aliasesRu: <String>['паста в сливочном соусе'],
  ),
  _RecipePromptEntry(
    labelEn: 'Tomato soup',
    labelRu: 'Томатный суп',
    aliasesEn: <String>['tomato soup'],
    aliasesRu: <String>['суп из томатов'],
  ),
  _RecipePromptEntry(
    labelEn: 'Shakshuka',
    labelRu: 'Шакшука',
    aliasesEn: <String>['eggs in tomato sauce'],
    aliasesRu: <String>['яйца в томатном соусе'],
  ),
  _RecipePromptEntry(
    labelEn: 'Chicken soup',
    labelRu: 'Куриный суп',
    aliasesEn: <String>['broth soup'],
    aliasesRu: <String>['суп с курицей'],
  ),
  _RecipePromptEntry(
    labelEn: 'Mushroom risotto',
    labelRu: 'Грибное ризотто',
    aliasesEn: <String>['risotto'],
    aliasesRu: <String>['ризотто с грибами'],
  ),
  _RecipePromptEntry(
    labelEn: 'Baked salmon',
    labelRu: 'Запеченный лосось',
    aliasesEn: <String>['salmon fillet'],
    aliasesRu: <String>['лосось в духовке'],
  ),
  _RecipePromptEntry(
    labelEn: 'Greek salad',
    labelRu: 'Греческий салат',
    aliasesEn: <String>['feta salad'],
    aliasesRu: <String>['салат с фетой'],
  ),
  _RecipePromptEntry(
    labelEn: 'Protein breakfast',
    labelRu: 'Белковый завтрак',
    aliasesEn: <String>['high protein breakfast'],
    aliasesRu: <String>['завтрак с белком'],
  ),
  _RecipePromptEntry(
    labelEn: 'Avocado toast',
    labelRu: 'Тост с авокадо',
    aliasesEn: <String>['toast'],
    aliasesRu: <String>['тосты'],
  ),
  _RecipePromptEntry(
    labelEn: 'Chicken curry',
    labelRu: 'Куриное карри',
    aliasesEn: <String>['curry'],
    aliasesRu: <String>['карри'],
  ),
  _RecipePromptEntry(
    labelEn: 'Lentil soup',
    labelRu: 'Чечевичный суп',
    aliasesEn: <String>['lentils'],
    aliasesRu: <String>['суп из чечевицы'],
  ),
  _RecipePromptEntry(
    labelEn: 'Veggie omelette',
    labelRu: 'Омлет с овощами',
    aliasesEn: <String>['omelette'],
    aliasesRu: <String>['омлет'],
  ),
];

const List<_MealPromptEntry> _mealPrompts = <_MealPromptEntry>[
  _MealPromptEntry(
    labelEn: 'Oatmeal with berries',
    labelRu: 'Овсянка с ягодами',
    calories: 320,
    protein: 11,
    fat: 8,
    carbs: 49,
    aliasesEn: <String>['oatmeal', 'porridge'],
    aliasesRu: <String>['каша', 'овсяная каша'],
  ),
  _MealPromptEntry(
    labelEn: 'Greek yogurt bowl',
    labelRu: 'Боул с греческим йогуртом',
    calories: 290,
    protein: 21,
    fat: 8,
    carbs: 28,
    aliasesEn: <String>['yogurt bowl'],
    aliasesRu: <String>['йогурт с ягодами'],
  ),
  _MealPromptEntry(
    labelEn: 'Scrambled eggs',
    labelRu: 'Яичница-болтунья',
    calories: 260,
    protein: 18,
    fat: 19,
    carbs: 3,
    aliasesEn: <String>['eggs'],
    aliasesRu: <String>['яичница'],
  ),
  _MealPromptEntry(
    labelEn: 'Omelette with cheese',
    labelRu: 'Омлет с сыром',
    calories: 340,
    protein: 24,
    fat: 25,
    carbs: 4,
    aliasesEn: <String>['omelette'],
    aliasesRu: <String>['омлет'],
  ),
  _MealPromptEntry(
    labelEn: 'Cottage cheese with fruit',
    labelRu: 'Творог с фруктами',
    calories: 280,
    protein: 24,
    fat: 6,
    carbs: 29,
    aliasesEn: <String>['cottage cheese'],
    aliasesRu: <String>['творог'],
  ),
  _MealPromptEntry(
    labelEn: 'Protein pancakes',
    labelRu: 'Протеиновые панкейки',
    calories: 370,
    protein: 26,
    fat: 10,
    carbs: 42,
    aliasesEn: <String>['pancakes'],
    aliasesRu: <String>['панкейки'],
  ),
  _MealPromptEntry(
    labelEn: 'Chicken and rice',
    labelRu: 'Курица с рисом',
    calories: 510,
    protein: 38,
    fat: 12,
    carbs: 58,
    aliasesEn: <String>['rice with chicken'],
    aliasesRu: <String>['рис с курицей'],
  ),
  _MealPromptEntry(
    labelEn: 'Turkey with buckwheat',
    labelRu: 'Индейка с гречкой',
    calories: 470,
    protein: 37,
    fat: 11,
    carbs: 46,
    aliasesEn: <String>['turkey buckwheat'],
    aliasesRu: <String>['гречка с индейкой'],
  ),
  _MealPromptEntry(
    labelEn: 'Salmon with vegetables',
    labelRu: 'Лосось с овощами',
    calories: 460,
    protein: 34,
    fat: 26,
    carbs: 16,
    aliasesEn: <String>['salmon'],
    aliasesRu: <String>['рыба с овощами'],
  ),
  _MealPromptEntry(
    labelEn: 'Chicken Caesar salad',
    labelRu: 'Салат Цезарь с курицей',
    calories: 430,
    protein: 31,
    fat: 24,
    carbs: 20,
    aliasesEn: <String>['caesar salad'],
    aliasesRu: <String>['цезарь'],
  ),
  _MealPromptEntry(
    labelEn: 'Greek salad',
    labelRu: 'Греческий салат',
    calories: 290,
    protein: 10,
    fat: 22,
    carbs: 12,
    aliasesEn: <String>['feta salad'],
    aliasesRu: <String>['салат с фетой'],
  ),
  _MealPromptEntry(
    labelEn: 'Chicken pasta',
    labelRu: 'Паста с курицей',
    calories: 560,
    protein: 33,
    fat: 14,
    carbs: 70,
    aliasesEn: <String>['pasta'],
    aliasesRu: <String>['макароны с курицей'],
  ),
  _MealPromptEntry(
    labelEn: 'Bolognese pasta',
    labelRu: 'Паста болоньезе',
    calories: 610,
    protein: 28,
    fat: 21,
    carbs: 74,
    aliasesEn: <String>['bolognese'],
    aliasesRu: <String>['болоньезе'],
  ),
  _MealPromptEntry(
    labelEn: 'Rice bowl with shrimp',
    labelRu: 'Боул с рисом и креветками',
    calories: 520,
    protein: 29,
    fat: 14,
    carbs: 65,
    aliasesEn: <String>['shrimp bowl'],
    aliasesRu: <String>['боул с креветками'],
  ),
  _MealPromptEntry(
    labelEn: 'Chicken curry with rice',
    labelRu: 'Куриное карри с рисом',
    calories: 590,
    protein: 35,
    fat: 20,
    carbs: 63,
    aliasesEn: <String>['curry'],
    aliasesRu: <String>['карри'],
  ),
  _MealPromptEntry(
    labelEn: 'Tomato soup',
    labelRu: 'Томатный суп',
    calories: 210,
    protein: 5,
    fat: 8,
    carbs: 27,
    aliasesEn: <String>['soup'],
    aliasesRu: <String>['суп'],
  ),
  _MealPromptEntry(
    labelEn: 'Chicken soup',
    labelRu: 'Куриный суп',
    calories: 260,
    protein: 18,
    fat: 9,
    carbs: 21,
    aliasesEn: <String>['broth'],
    aliasesRu: <String>['бульон'],
  ),
  _MealPromptEntry(
    labelEn: 'Lentil soup',
    labelRu: 'Чечевичный суп',
    calories: 310,
    protein: 17,
    fat: 7,
    carbs: 41,
    aliasesEn: <String>['lentils soup'],
    aliasesRu: <String>['суп из чечевицы'],
  ),
  _MealPromptEntry(
    labelEn: 'Beef stew',
    labelRu: 'Тушеная говядина',
    calories: 480,
    protein: 34,
    fat: 25,
    carbs: 18,
    aliasesEn: <String>['stew'],
    aliasesRu: <String>['рагу'],
  ),
  _MealPromptEntry(
    labelEn: 'Turkey cutlets',
    labelRu: 'Котлеты из индейки',
    calories: 410,
    protein: 33,
    fat: 21,
    carbs: 16,
  ),
  _MealPromptEntry(
    labelEn: 'Buckwheat with mushrooms',
    labelRu: 'Гречка с грибами',
    calories: 360,
    protein: 11,
    fat: 9,
    carbs: 56,
  ),
  _MealPromptEntry(
    labelEn: 'Sushi rolls',
    labelRu: 'Суши роллы',
    calories: 420,
    protein: 15,
    fat: 9,
    carbs: 66,
    aliasesEn: <String>['sushi'],
    aliasesRu: <String>['роллы'],
  ),
  _MealPromptEntry(
    labelEn: 'Avocado toast',
    labelRu: 'Тост с авокадо',
    calories: 340,
    protein: 9,
    fat: 17,
    carbs: 36,
    aliasesEn: <String>['toast'],
    aliasesRu: <String>['тост'],
  ),
  _MealPromptEntry(
    labelEn: 'Sandwich with ham and cheese',
    labelRu: 'Сэндвич с ветчиной и сыром',
    calories: 430,
    protein: 22,
    fat: 19,
    carbs: 39,
    aliasesEn: <String>['sandwich'],
    aliasesRu: <String>['бутерброд'],
  ),
  _MealPromptEntry(
    labelEn: 'Chicken shawarma',
    labelRu: 'Шаурма с курицей',
    calories: 620,
    protein: 31,
    fat: 26,
    carbs: 60,
    aliasesEn: <String>['shawarma', 'wrap'],
    aliasesRu: <String>['шаверма'],
  ),
  _MealPromptEntry(
    labelEn: 'Protein smoothie',
    labelRu: 'Протеиновый смузи',
    calories: 280,
    protein: 24,
    fat: 6,
    carbs: 29,
    aliasesEn: <String>['smoothie'],
    aliasesRu: <String>['смузи'],
  ),
  _MealPromptEntry(
    labelEn: 'Fruit smoothie bowl',
    labelRu: 'Смузи-боул с фруктами',
    calories: 330,
    protein: 10,
    fat: 8,
    carbs: 53,
  ),
  _MealPromptEntry(
    labelEn: 'Yogurt with granola',
    labelRu: 'Йогурт с гранолой',
    calories: 350,
    protein: 16,
    fat: 10,
    carbs: 47,
  ),
  _MealPromptEntry(
    labelEn: 'Cheesecakes',
    labelRu: 'Сырники',
    calories: 390,
    protein: 22,
    fat: 14,
    carbs: 42,
    aliasesEn: <String>['cottage cheese pancakes'],
    aliasesRu: <String>['творожники'],
  ),
  _MealPromptEntry(
    labelEn: 'Baked potatoes with chicken',
    labelRu: 'Запеченный картофель с курицей',
    calories: 540,
    protein: 34,
    fat: 15,
    carbs: 63,
  ),
  _MealPromptEntry(
    labelEn: 'Mashed potatoes with cutlet',
    labelRu: 'Пюре с котлетой',
    calories: 610,
    protein: 27,
    fat: 27,
    carbs: 58,
  ),
  _MealPromptEntry(
    labelEn: 'Chicken nuggets with salad',
    labelRu: 'Куриные наггетсы с салатом',
    calories: 490,
    protein: 25,
    fat: 24,
    carbs: 39,
  ),
  _MealPromptEntry(
    labelEn: 'Tuna salad',
    labelRu: 'Салат с тунцом',
    calories: 320,
    protein: 27,
    fat: 16,
    carbs: 13,
  ),
  _MealPromptEntry(
    labelEn: 'Shrimp pasta',
    labelRu: 'Паста с креветками',
    calories: 570,
    protein: 29,
    fat: 16,
    carbs: 71,
  ),
  _MealPromptEntry(
    labelEn: 'Poke bowl',
    labelRu: 'Поке боул',
    calories: 540,
    protein: 28,
    fat: 17,
    carbs: 64,
  ),
  _MealPromptEntry(
    labelEn: 'Chicken burger',
    labelRu: 'Куриный бургер',
    calories: 610,
    protein: 32,
    fat: 28,
    carbs: 52,
  ),
  _MealPromptEntry(
    labelEn: 'Beef burger',
    labelRu: 'Говяжий бургер',
    calories: 690,
    protein: 31,
    fat: 38,
    carbs: 50,
  ),
  _MealPromptEntry(
    labelEn: 'Pizza slice',
    labelRu: 'Кусок пиццы',
    calories: 300,
    protein: 12,
    fat: 11,
    carbs: 37,
    aliasesEn: <String>['pizza'],
    aliasesRu: <String>['пицца'],
  ),
  _MealPromptEntry(
    labelEn: 'Varenyky',
    labelRu: 'Вареники',
    calories: 430,
    protein: 13,
    fat: 9,
    carbs: 72,
  ),
  _MealPromptEntry(
    labelEn: 'Pelmeni',
    labelRu: 'Пельмени',
    calories: 520,
    protein: 24,
    fat: 21,
    carbs: 56,
  ),
  _MealPromptEntry(
    labelEn: 'Soba noodles',
    labelRu: 'Лапша соба',
    calories: 430,
    protein: 14,
    fat: 9,
    carbs: 69,
  ),
  _MealPromptEntry(
    labelEn: 'Tofu stir fry',
    labelRu: 'Тофу с овощами',
    calories: 390,
    protein: 23,
    fat: 17,
    carbs: 31,
  ),
  _MealPromptEntry(
    labelEn: 'Quinoa bowl',
    labelRu: 'Боул с киноа',
    calories: 410,
    protein: 16,
    fat: 14,
    carbs: 50,
  ),
  _MealPromptEntry(
    labelEn: 'Chicken wraps',
    labelRu: 'Ролл с курицей',
    calories: 470,
    protein: 27,
    fat: 15,
    carbs: 54,
  ),
  _MealPromptEntry(
    labelEn: 'Cottage cheese casserole',
    labelRu: 'Творожная запеканка',
    calories: 360,
    protein: 23,
    fat: 11,
    carbs: 40,
  ),
  _MealPromptEntry(
    labelEn: 'Rice porridge',
    labelRu: 'Рисовая каша',
    calories: 290,
    protein: 7,
    fat: 6,
    carbs: 51,
  ),
  _MealPromptEntry(
    labelEn: 'Pasta with tuna',
    labelRu: 'Паста с тунцом',
    calories: 540,
    protein: 33,
    fat: 14,
    carbs: 66,
  ),
  _MealPromptEntry(
    labelEn: 'Vegetable stew',
    labelRu: 'Овощное рагу',
    calories: 250,
    protein: 7,
    fat: 9,
    carbs: 34,
  ),
  _MealPromptEntry(
    labelEn: 'Stuffed peppers',
    labelRu: 'Фаршированный перец',
    calories: 430,
    protein: 24,
    fat: 16,
    carbs: 42,
  ),
];
